### ISSUE TITLE
Add Letters & Seals

### ISSUE THREAD

**Issue by Omertron** [mihaeu/istanbul-generator#1]
Is there any chance that letters and seals can be added?

**Comment by mihaeu** [comment]
Sure, this or next weekend I should have some free time.

Any other features you're missing?

**Comment by Omertron** [comment]
Don't think so. 

I normally swap the pegasus depot out for the post office, but that's not something I need help with ;)

**Comment by mihaeu** [comment]
Added the extension with Mocha & Baksheesh (Great Bazaar) and without. Let me know if it looks fine for you or if you're interested in any other feature.

**Comment by Omertron** [comment]
Excellent, thanks :+1:
